name: Deploy the promptflow Template

on:
  workflow_dispatch:


env:
  AZURE_RESOURCE_GROUP: "LAB3GPTDEVRG01"
  AZURE_ML_WORKSPACE: "labmltest02"
  AZURE_SUBSCRIPTION_ID: "20dd0807-4bab-40e8-a83e-75a1f4548c29"


jobs:
  create_and_run_flow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Azure CLI and ML extension
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az extension add -n ml -y

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_DEVOPS_CREDENTIALS }}

    - name: Set Azure subscription
      run: |
        az account set --subscription ${{ env.AZURE_SUBSCRIPTION_ID }}

    - name: Set Azure ML defaults
      run: |
        az configure --defaults group=${{ env.AZURE_RESOURCE_GROUP }} workspace=${{ env.AZURE_ML_WORKSPACE }}

    - name: Deploy to Azure ML Studio - labmltest02
      run: |
        
        #python -m pip install --upgrade pip                
        #pip install promptflow-azure
        # Navigate to the rag_flow_0 directory run05
        #cd src/Woodside_Prompltflow_RagQnA
        # Install Python dependencies specific to woodside_promptflow_rag01
        #pip install -r requirements.txt


        #creating Main FLow 
      
        # Deploy the flow using az prompt-flow
        #pfazure flow create \
        #  --flow . \
        #  --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
        #  --workspace-name ${{ env.AZURE_ML_WORKSPACE }} \
        #  --set display_name=woodside_promptflow_ragQnA01     


    - name: Deploy to Azure ML Studio - eval-groundedness
      run: |
        
        python -m pip install --upgrade pip                
        pip install promptflow-azure
        # Navigate to the rag_flow_0 directory run05

        #creating Evaluation 
        cd src/evaluation/eval-QnA-Groundness
        # Install Python dependencies specific to eval-groundedness
        pip install -r requirements.txt

        # Deploy the flow using az prompt-flow
        pfazure flow create \
          --flow . \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --workspace-name ${{ env.AZURE_ML_WORKSPACE }} \
          --set display_name=eval-groundedness-ragQnA01

    - name: Deploy to Azure ML Studio - eval-QnA-Coherence
      run: |
        
        python -m pip install --upgrade pip                
        pip install promptflow-azure
        # Navigate to the rag_flow_0 directory run23
        cd src/evaluation/eval-QnA-Coherence
        # Install Python dependencies specific to eval-single-turn-metrics
        pip install -r requirements.txt

        # Deploy the flow using az prompt-flow
        pfazure flow create \
          --flow . \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --workspace-name ${{ env.AZURE_ML_WORKSPACE }} \
          --set display_name=eval-Coherence_ragQnA01

    - name: Deploy to Azure ML Studio - eval-QnA-Fluency
      run: |
        
        python -m pip install --upgrade pip                
        pip install promptflow-azure
        # Navigate to the eval-perceived-intelligence directory
        cd src/evaluation/eval-QnA-Fluency
        # Install Python dependencies specific to eval-perceived-intelligence
        pip install -r requirements.txt

        # Deploy the flow using az prompt-flow
        pfazure flow create \
          --flow . \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --workspace-name ${{ env.AZURE_ML_WORKSPACE }} \
          --set display_name=eval-QnA-Fluency-ragQnA01

    - name: Deploy to Azure ML Studio - eval-QnA-Relevance
      run: |
        
        python -m pip install --upgrade pip                
        pip install promptflow-azure
        # Navigate to the eval-qna-non-rag directory
        cd src/evaluation/eval-QnA-Relevance
        # Install Python dependencies specific to eval-qna-non-rag
        pip install -r requirements.txt

        # Deploy the flow using az prompt-flow
        pfazure flow create \
          --flow . \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --workspace-name ${{ env.AZURE_ML_WORKSPACE }} \
          --set display_name=eval-QnA-Relevance-ragQnA01