name: Deploy the promptflow Template

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  create_and_run_flow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Azure CLI and ML extension
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az extension add -n ml -y

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_DEVOPS_CREDENTIALS }}

    - name: Set Azure subscription
      run: |
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set Azure ML defaults
      run: |
        az configure --defaults group=${{ secrets.AZURE_RESOURCE_GROUP }} workspace=${{ secrets.AZURE_ML_WORKSPACE }}

    - name: Deploy to Azure ML Studio - woodside_promptflow_rag01
      run: |
        
        python -m pip install --upgrade pip                
        pip install promptflow-azure
        # Navigate to the rag_flow_0 directory run05
        cd src/woodside_promptflow_rag01
        # Install Python dependencies specific to woodside_promptflow_rag01
        pip install -r requirements.txt

        # Deploy the flow using az prompt-flow
        pfazure flow create \
          --flow . \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --workspace-name ${{ secrets.AZURE_ML_WORKSPACE }} \
          --set display_name=woodside_promptflow_rag01     


    - name: Deploy to Azure ML Studio - eval-groundedness
      run: |
        
        python -m pip install --upgrade pip                
        pip install promptflow-azure
        # Navigate to the rag_flow_0 directory run05
        cd src/evaluation/eval-groundedness
        # Install Python dependencies specific to eval-groundedness
        pip install -r requirements.txt

        # Deploy the flow using az prompt-flow
        pfazure flow create \
          --flow . \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --workspace-name ${{ secrets.AZURE_ML_WORKSPACE }} \
          --set display_name=eval-groundedness

    - name: Deploy to Azure ML Studio - eval-single-turn-metrics
      run: |
        
        python -m pip install --upgrade pip                
        pip install promptflow-azure
        # Navigate to the rag_flow_0 directory run23
        cd src/evaluation/eval-single-turn-metrics
        # Install Python dependencies specific to eval-single-turn-metrics
        pip install -r requirements.txt

        # Deploy the flow using az prompt-flow
        pfazure flow create \
          --flow . \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --workspace-name ${{ secrets.AZURE_ML_WORKSPACE }} \
          --set display_name=eval-single-turn-metrics

    - name: Deploy to Azure ML Studio - eval-perceived-intelligence
      run: |
        
        python -m pip install --upgrade pip                
        pip install promptflow-azure
        # Navigate to the eval-perceived-intelligence directory
        cd src/evaluation/eval-perceived-intelligence
        # Install Python dependencies specific to eval-perceived-intelligence
        pip install -r requirements.txt

        # Deploy the flow using az prompt-flow
        pfazure flow create \
          --flow . \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --workspace-name ${{ secrets.AZURE_ML_WORKSPACE }} \
          --set display_name=eval-perceived-intelligence

    - name: Deploy to Azure ML Studio - eval-qna-non-rag
      run: |
        
        python -m pip install --upgrade pip                
        pip install promptflow-azure
        # Navigate to the eval-qna-non-rag directory
        cd src/evaluation/eval-qna-non-rag
        # Install Python dependencies specific to eval-qna-non-rag
        pip install -r requirements.txt

        # Deploy the flow using az prompt-flow
        pfazure flow create \
          --flow . \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --workspace-name ${{ secrets.AZURE_ML_WORKSPACE }} \
          --set display_name=eval-qna-non-rag